platform :ios,'14.0'
flutter_application_path = '../flutter_seat_table/'
load File.join(flutter_application_path, '.ios', 'Flutter', 'podhelper.rb')
target 'ExamAssistant_T' do
  use_frameworks!
  install_all_flutter_pods(flutter_application_path)
end
